apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: production
data:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service.production.svc.cluster.local:5672/"
  LOG_LEVEL: "info"
  PORT: "8000"
